### ISSUE TITLE
Unifi OS 4.x and pyunifiprotect breaking changes

### ISSUE THREAD

**Issue by mmolitor87** [ep1cman/unifi-protect-backup#148] opened 2024-05-18 03:10 UTC
Unifi Protect Backup 0.10.7 works with Unifi Protect 4.0.7 and 4.0.19 work without changes, however Unifi OS 4.x and pyunifiprotect are introducing breaking changes.

Unifi OS 4.0.3 changes the cookie names: https://github.com/AngellusMortis/pyunifiprotect/issues/382

This PR resolves it: https://github.com/AngellusMortis/pyunifiprotect/pull/388

There is also a PR that refactors Unifi OS auth in a seemingly breaking change: https://github.com/AngellusMortis/pyunifiprotect/pull/391

Both PRs are merged but there isn't a new version yet.

**Comment by ep1cman** [comment] 2024-05-18 10:18
If I produce a dev build with these changes included would you be able to test them? 

Unfortunately I only have one unifi setup which I won't upgrade to EA because last time I tried it broke everything and I had to factory reset everything

**Comment by cyberpower678** [comment] 2024-05-22 12:05
If you can put it into a docker, and give me the tag name, I can.

**Comment by mmolitor87** [comment] 2024-05-27 18:48
> If I produce a dev build with these changes included would you be able to test them?
> 
> Unfortunately I only have one unifi setup which I won't upgrade to EA because last time I tried it broke everything and I had to factory reset everything

Yes! It looks like punifiprotect has a release that includes these PRs now. I can test it out.

**Comment by ep1cman** [comment] 2024-05-27 22:16
The dev container has been updated to the latest version of pyunifiprotect. Let me know if that works without any other changes

**Comment by mmolitor87** [comment] 2024-06-05 19:14
Sorry it took so long, but I finally got around to testing it. Predictably ended up with the same error in https://github.com/ep1cman/unifi-protect-backup/issues/151

I know you're low on time right now so I'll patiently wait. I can test whatever dev builds you push.

**Comment by ep1cman** [comment] 2024-06-05 23:45
there should be a new build shortly that fixes #151 in the dev container, if you can confirm this works with 4.x.x I will push a new release. My UDM still hasn't gotten the update.

**Comment by mmolitor87** [comment] 2024-06-06 03:30
> there should be a new build shortly that fixes #151 in the dev container, if you can confirm this works with 4.x.x I will push a new release. My UDM still hasn't gotten the update.

Working a lot better now. The previous error is gone, but now there's this:

`2024-06-05 22:29:03 [   ERROR   ] unifi_protect_backup.missing_event_checker :  Unexpected exception occurred during missing event check:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/missing_event_checker.py", line 151, in start
    async for event in self._get_missing_events():
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/missing_event_checker.py", line 65, in _get_missing_events
    events_chunk = await self._protect.get_events(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 786, in get_events
    response = await self.get_events_raw(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 745, in get_events_raw
    return await self.api_request_list("events", params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 316, in api_request_list
    data = await self.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 274, in api_request
    data = await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 249, in api_request_raw
    await self._os.verify_response(url, response)
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 332, in verify_response
    raise NotAuthorized(msg % (url, response.status, reason))
pyunifiprotect.exceptions.NotAuthorized: Request failed: /proxy/protect/api/events - Status: 401 - Reason: {'code': 401, 'message': 'Unauthorized'}
`

**Comment by ep1cman** [comment] 2024-06-06 23:18
My UDM still hasn't gotten the update so I am unable to test this to figure out why this is happening. I saw people on the home assistant forums saying creating a new local only user fixed issues, so maybe try that?

**Comment by mmolitor87** [comment] 2024-06-07 03:46
> My UDM still hasn't gotten the update so I am unable to test this to figure out why this is happening. I saw people on the home assistant forums saying creating a new local only user fixed issues, so maybe try that?

I recreated the local user for UPB and it made no difference. I even tested setting it as a super admin which had no difference. I switched it back to the custom role denying console OS access.

**Comment by ep1cman** [comment] 2024-06-07 19:13
I have tracked down the issue, it is caused by Unifi Protect returning invalid cookies, which means pyunifiprotect is then not re-using the session token, triggering a rate-limit on authentication:
https://github.com/AngellusMortis/pyunifiprotect/issues/401

**Comment by ronytomen** [comment] 2024-06-12 02:23
It would appear that the `pyunifiprotect` repository has been deleted or made private. 

Maybe it is time to move to the fork? 
https://github.com/uilibs/uiprotect

**Comment by ep1cman** [comment] 2024-06-12 08:52
@ronytomen thanks for the heads up. I will make the switch. I suspected this might happen so already forked pyunifiprotect for this projects use incase something happened to it

**Comment by cyberpower678** [comment] 2024-06-12 11:36
Wow.  Wtf?  I’m glad I just moved my pull request changes from there yesterday.

**Comment by ep1cman** [comment] 2024-06-12 11:43
Looks like it's been pulled off PyPI too which is an issue. I will be switching to the new fork as soon as the new downloader is merged, I'll have everything prepped to go

**Comment by cyberpower678** [comment] 2024-06-12 12:08
It would appear bdraco was the original dev of the library to begin with, so no major issue here with it having been moved to a new location.  They seem super chill and am hoping I can sign on as a maintainer with them, once I learn how he would like certain things done on that repo. :p

**Comment by cyberpower678** [comment] 2024-06-12 12:21
Actually a user named briis was, then forked to bdraco, then forked to AngellusMortis.  briis has archived their repository.  Just a fun fact.

**Comment by ep1cman** [comment] 2024-06-12 12:22
If you check the bottom of the readme I think it still lists briis, because I've been too lazy to update it 😅

**Comment by ep1cman** [comment] 2024-06-12 21:39
Can folks confirm if the latest release has addressed this now? Locally for me it seems to work now with 4.x.x

**Comment by natehudson** [comment] 2024-06-12 21:43
I upgraded to Protect `4.0.33` today and pulled the latest docker image. Everything is working for me but I have a mix of G3/G4/G5 cameras, nothing fancy.

**Comment by cyberpower678** [comment] 2024-06-12 22:04
Still working for me on experimental.

**Comment by Swallowtail23** [comment] 2024-06-12 22:06
> I upgraded to Protect `4.0.33` today and pulled the latest docker image. Everything is working for me but I have a mix of G3/G4/G5 cameras, nothing fancy.

The issues are with Unifi OS 4.x, not Protect 4.x

**Comment by natehudson** [comment] 2024-06-12 22:24
> > I upgraded to Protect `4.0.33` today and pulled the latest docker image. Everything is working for me but I have a mix of G3/G4/G5 cameras, nothing fancy.
> 
> The issues are with Unifi OS 4.x, not Protect 4.x

My bad, I misunderstood.

**Comment by mmolitor87** [comment] 2024-06-12 23:10
> Can folks confirm if the latest release has addressed this now? Locally for me it seems to work now with 4.x.x

It has been working fine for me since June 5th on the latest release.

**Comment by bjkcubed** [comment] 2024-07-07 19:14
I'm still having issues, setup below to compare:

- Updated UniFi OS to v4.0.6
- Older version of unifi-protect-backup was failing on same "Unauthorized" message as above.

Updated to the latest docker image.  Long story short... it didn't work.  So I started to reset/debug locally.

I reset everything to test:

- Removed sqlite database
- Deleted container, created new
- Same rclone.conf pushing to S3
- Formatted UNVR drives so no old events

Fresh start:
- 10 or so events existed, downloaded from the NVR and uploaded to S3 just like before.  I thought success!
- Then some new events were created and I saw this log:

```
2024-07-07 18:14:24 [   DEBUG   ] unifi_protect_backup.event_listener        :  Adding event 668adaf5038c8603e40004ea to queue (Current download queue=3)
2024-07-07 18:14:59 [   DEBUG   ] unifi_protect_backup.event_listener        :  Adding event 668adb0201c98603e40004ef to queue (Current download queue=4)
2024-07-07 18:15:31 [   DEBUG   ] unifi_protect_backup.event_listener        :  Adding event 668adb2702088603e40004fb to queue (Current download queue=5)
2024-07-07 18:15:35 [   DEBUG   ] unifi_protect_backup.missing_event_checker :  Running check for missing events...
2024-07-07 18:15:43 [  WARNING  ] unifi_protect_backup.downloader            : [668ad8bd02568603e4000454]      Failed download attempt 1, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/downloader.py", line 184, in _download
    video = await self._protect.get_camera_video(event.camera_id, event.start, event.end)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 1411, in get_camera_video
    return await self.export_camera_video(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 1333, in export_camera_video
    return await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 239, in api_request_raw
    response = await self._os.request(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 378, in request
    response = await req_context.__aenter__()  # noqa: PLC2801
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 971, in start
    with self._timer:
  File "/usr/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
```

- Several additional TimeoutError followed.  Then this updated event:

```2024-07-07 18:35:35 [   DEBUG   ] unifi_protect_backup.missing_event_checker :  Running check for missing events...
2024-07-07 18:35:51 [  WARNING  ] unifi_protect_backup.downloader            : [668ad8bd02568603e4000454]      Failed download attempt 5, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/downloader.py", line 184, in _download
    video = await self._protect.get_camera_video(event.camera_id, event.start, event.end)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 1411, in get_camera_video
    return await self.export_camera_video(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 1333, in export_camera_video
    return await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 239, in api_request_raw
    response = await self._os.request(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 378, in request
    response = await req_context.__aenter__()  # noqa: PLC2801
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 971, in start
    with self._timer:
  File "/usr/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError
2024-07-07 18:35:52 [   ERROR   ] unifi_protect_backup.downloader            : [668ad8bd02568603e4000454]  Download failed after 5 attempts, abandoning event 668ad8bd02568603e4000454:
2024-07-07 18:35:52 [  WARNING  ] unifi_protect_backup.downloader            : [668ad8bd02568603e4000454]  Event failed download attempt 1
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/downloader.py", line 145, in start
    assert video is not None
           ^^^^^^^^^^^^^^^^^
AssertionError
```

- Afterwards all the items in the queue were downloaded/uploaded as usual.
- TimeoutError errors followed.  Seems to loop.  Rinse and repeat.

Any other logs be helpful?

**Closed** 2024-08-06 23:47 UTC
Labels: help wanted
